apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
data:
  HTTP_PORT: {{ .Values.service.port | quote }}
  {{- with .Values.ui }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.client }}
  {{ $_ := unset . "ssl" }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.java }}
    {{- toYaml . | nindent 2 }}
  {{- end }}