apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zoonavigator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zoonavigator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zoonavigator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "zoonavigator.fullname" . }}
          {{- if .Values.client.ssl.ZK_CLIENT_SECURE }}
          volumeMounts:
            - name: "truststore"
              mountPath: {{ .Values.client.ssl.truststore.mountPath }}
              subPath: {{ .Values.client.ssl.truststore.subPath }}
              readOnly: {{ .Values.client.ssl.truststore.readOnly }}  
            - name: "keystore"
              mountPath: {{ .Values.client.ssl.keystore.mountPath }}
              subPath: {{ .Values.client.ssl.keystore.subPath }}
              readOnly: {{ .Values.client.ssl.keystore.readOnly }}  
          {{- end}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.client.ssl.ZK_CLIENT_SECURE }}
      volumes:
        - name: "truststore"
          secret:
            secretName: {{ .Values.client.ssl.truststore.secretName }}
            optional: {{ .Values.client.ssl.truststore.optional}}
        - name: "keystore"
          secret:
            secretName: {{ .Values.client.ssl.keystore.secretName }}
            optional: {{ .Values.client.ssl.truststore.optional}}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}