{{- if eq .Values.client.ssl.ZK_CLIENT_SECURE "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
type: Opaque
data:
    ZK_CLIENT_SECURE: 'true'
    ZK_CLIENT_CNXN_SOCKET: ''
    ZK_SSL_KEYSTORE_PASSWORD: {{ .Values.client.ssl.keystore.password }}
    ZK_SSL_TRUSTSTORE_PASSWORD: {{ .Values.client.ssl.trustore.password }}
    # {{- toYaml .Values.client.ssl | b64enc | nindent 2 }}
{{- end -}}