apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
type: Opaque
data:
    ZK_CLIENT_SECURE: {{.Values.client.ssl.ZK_CLIENT_SECURE | quote | b64enc}}
    ZK_CLIENT_CNXN_SOCKET: {{ .Values.client.ssl.ZK_CLIENT_SECURE | ternary "org.apache.zookeeper.ClientCnxnSocketNetty" "org.apache.zookeeper.ClientCnxnSocketNIO" | quote | b64enc}}
{{- if .Values.client.ssl.ZK_CLIENT_SECURE }}
    ZK_SSL_KEYSTORE_PASSWORD: {{ .Values.client.ssl.keystore.password | quote | b64enc}}
    ZK_SSL_TRUSTSTORE_PASSWORD: {{ .Values.client.ssl.truststore.password | quote | b64enc}}
    ZK_SSL_TRUSTSTORE_PATH: {{printf "%s/%s" .Values.client.ssl.truststore.mountPath .Values.client.ssl.truststore.subPath | quote | b64enc}}
    ZK_SSL_KEYSTORE_PATH: {{printf "%s/%s" .Values.client.ssl.keystore.mountPath .Values.client.ssl.keystore.subPath | quote | b64enc}}
{{- end}}