apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.client }}
    {{- toYaml . | b64enc | nindent 2 }}
  {{- end }}