apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zoonavigator.fullname" . }}
  labels:
    {{- include "zoonavigator.labels" . | nindent 4 }}
type: Opaque
data:
    ZK_CLIENT_SECURE: {{.Values.client.ssl.ZK_CLIENT_SECURE}}
{{- if eq .Values.client.ssl.ZK_CLIENT_SECURE "true" }}
    ZK_CLIENT_CNXN_SOCKET: 'org.apache.zookeeper.ClientCnxnSocketNetty'
    ZK_SSL_KEYSTORE_PASSWORD: {{ .Values.client.ssl.keystore.password }}
    ZK_SSL_TRUSTSTORE_PASSWORD: {{ .Values.client.ssl.truststore.password }}
    ZK_SSL_TRUSTSTORE_PATH: "{{.Values.client.ssl.truststore.mountPath}}/{{.Values.client.ssl.truststore.subPath}}"
    ZK_SSL_KEYSTORE_PATH: '{{.Values.client.ssl.keystore.mountPath}}/{{.Values.client.ssl.keystore.subPath}}'
{{- else -}}
    ZK_CLIENT_CNXN_SOCKET: "org.apache.zookeeper.ClientCnxnSocketNIO"
{{- end }}